<?php

declare(strict_types=1);

namespace App\Services\TempUsers;

use Arr;

class RandomNames
{
    private array $lastName = [
        'Orc',
        'Elf',
        'Mutant',
        'Dwarf',
        'Golem',
        'Goblin',
        'Zerg',
        'Protoss',
        'Goomba',
        'Eldar',
        'Tau',
        'Space Marine',
        'Chaos',
        'Tyranid',
        'Night Elf',
        'Draenei',
        'Worsen',
        'Paren',
        'Dracthyr',
        'Undead',
        'Lauren',
        'Troll',
        'Blood Elf',
        'Gnome',
        'Koopa',
        'Void Elf',
        'Argonian',
        'Kobold',
        'Gerudo',
        'Gnoll',
        'Halfling',
        'Inkling',
        'Khajiit',
        'Korok',
        'Octoling',
        'Toad',
        'Zora',
        'Leach',
        'Human',
        'Alien',
        'Gamer',
        'Dragonborn',
        'Bandicoot',
        'Metroid',
        'Pixel',
        'Batman',
        'Bomberman',
        'Skeleton',
        'Zombie',
        'Spaceship',
        'Assassin',
        'Barbarian',
        'Paladin',
        'Mage',
        'Sorcerer',
        'Necromancer',
        'Druid',
        'Bard',
        'The Witcher',
        'Warrior',
        'Summoner',
        'Archer',
        'Hunter',
        'Ranger',
        'Wizard',
        'Ninja',
        'Cleric',
        'Priest',
    ];

    private array $firstName = [
        'King',
        'Joel',
        'Kratos',
        'Agent',
        'Master',
        'Cloud',
        'Mario',
        'Samus',
        'Gordon',
        'Bowser',
        'Luigi',
        'Duke',
        'Doomguy',
        'Aloy',
        'Sonic',
        'Price',
        'Atreus',
        'Ratchet',
        'Cortana',
        'Rayman',
        'Samanosuke',
        'Sylvanas',
        'Alduin',
        'Steve',
        'Dogmeat',
        'Captain',
        'Isaac',
        'Tom',
        'Niko',
        'CJ',
        'Arthur',
        'Max',
        'Sam',
        'Little',
        'Lara',
        'Link',
        'Zelda',
        'Vaas',
        'Crash',
        'Glados',
        'Doom',
        'Leon',
        'Nick',
        'Ryu',
        'Fox',
        'Chloe',
    ];

    public function generate(): string
    {
        return Arr::random($this->firstName) . ' ' . Arr::random($this->lastName);
    }
}
